#!/bin/bash

VERSION_STRING=(`grep ELECTRUM_VERSION lib/version.py`)
ELECTRUM_QBC_VERSION=${VERSION_STRING[2]}
ELECTRUM_QBC_VERSION=${ELECTRUM_QBC_VERSION#\'}
ELECTRUM_QBC_VERSION=${ELECTRUM_QBC_VERSION%\'}
export ELECTRUM_QBC_VERSION
